services:
  - type: web
    name: phishx-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GEMINI_API_KEY
        sync: false
